# Generated by Django 6.0.5 on 2026-05-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Reviews',
        ),
    ]
