# Generated by Django 6.0.5 on 2026-05-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projecttitles_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttitles',
            name='domain',
            field=models.CharField(choices=[('VLSI', 'VLSI'), ('Embedded', 'Embedded'), ('IoT', 'IoT'), ('Wired Networks', 'Wired Networks'), ('Wireless Networks', 'Wireless Networks'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Full Stack', 'Full Stack'), ('AI', 'AI')], max_length=200),
        ),
    ]
