# Generated by Django 6.0.5 on 2026-05-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projecttitles_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttitles',
            name='domain',
            field=models.CharField(choices=[('VLSI', 'VLSI'), ('Embedded', 'Embedded'), ('IoT', 'IoT'), ('Software', 'Software')], max_length=200),
        ),
    ]
